name: Integrate
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: holepunchto/actions/node-base@v1
      - run: npm run lint
  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            platform: linux
          - os: ubuntu-24.04-arm
            platform: linux
          - os: macos-14
            platform: darwin
          - os: windows-2022
            platform: win32
    runs-on: ${{ matrix.os }}
    name: Test / ${{ matrix.platform }}
    steps:
      - uses: holepunchto/actions/bare-base@v1
      - run: |
          sudo apt install -y \
            gcc-aarch64-linux-gnu \
            g++-aarch64-linux-gnu \
            gcc-arm-linux-gnueabi \
            g++-arm-linux-gnueabi \
            gcc-i686-linux-gnu \
            g++-i686-linux-gnu \
            gcc-mips-linux-gnu \
            g++-mips-linux-gnu \
            gcc-mipsel-linux-gnu \
            g++-mipsel-linux-gnu \
            gcc-riscv64-linux-gnu \
            g++-riscv64-linux-gnu \
            gcc-x86-64-linux-gnu \
            g++-x86-64-linux-gnu
        if: ${{ matrix.platform == 'linux' }}
      - run: npm test
