name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            platform: linux
            arch: x64
          - os: ubuntu-22.04-arm64
            platform: linux
            arch: arm64
          - os: macos-14
            platform: darwin
            arch: arm64
          - os: windows-2022
            platform: win32
            arch: x64
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.platform }}-${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: sudo apt upgrade llvm
        if: ${{ matrix.platform == 'linux' }}
      - run: brew install llvm
        if: ${{ matrix.platform == 'darwin' }}
      - run: choco upgrade llvm
        if: ${{ matrix.platform == 'win32' }}
      - run: npm install
      - run: npm test
